# Ayudantía N°6:
### **Análisis de datos categóricos**
- Análisis univariado: Distribución de frecuencia: Tablas de frecuencia
- Análisis bivariado: Cruce de variables: Tablas de contingencia

## Antes de comenzar: trabajar con archivos en Google Colab

Esta ayudantía está preparada para ejecutarse en **Google Colab utilizando el entorno de ejecución de R**

Primero, sube a Colab el archivo:

`base_antropologia_limpia.xlsx`

Puedes hacerlo ejecutando la siguiente celda y seleccionando el archivo que descargaste en la página del curso desde tu computador

- Ruta:
/content/base_antropologia_limpia.xlsx

### 1. Cargar Paquetes

In [ ]:
system("apt-get update && apt-get install -y libmagick++-dev", intern = TRUE)
install.packages("summarytools") #Para no tener problemas con

In [12]:
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse,# Universo de paquetes : tidyr, dplyr, ggplot2,readr,purrr,tibble, stringr, forcats
               openxlsx,#Leer archivos xlsx
               readxl,#Leer archivos xl
               writexl,#Guardar tablas formato excel
               DataExplorer,#Exploración rápida
               summarytools,#Contiene la función freq() que muestra las frecuencias absolutas y relativas de una variable
               kableExtra,#Tablas elegantes
               webshot2,#Exportar tablas
               knitr,#Dar formato a las tablas
               gt)#Dar formato a las tablas

Loading required package: pacman

### 2. Importar base de datos

In [3]:
base <- read.xlsx("/content/base_antropologia_limpia.xlsx")

### 3. Explorar base

In [4]:
glimpse(base)

Rows: 147
Columns: 60
$ marca                                      <dbl> 45414.80, 45414.87, 45414.8…
$ direc                                      <chr> "", "", "", "", "", "rtoro@…
$ n_encuestador                              <chr> NA, NA, NA, NA, NA, NA, NA,…
$ sd_01                                      <chr> "Sí", "Sí", "Sí", "Sí", "Sí…
$ identidad_genero                           <chr> "Hombre cisgénero", "Mujer …
$ edad                                       <dbl> 23, 20, 22, 24, 24, 23, 21,…
$ año_ingreso_carrera                        <dbl> 2022, 2022, 2022, 2022, 202…
$ comuna                                     <chr> "lampa", "puente_alto", "pe…
$ clase_social                               <chr> "Clase social baja", "Clase…
$ nivel_educacion_padre                      <chr> "Educación Media", "Educaci…
$ nivel_educacion_madre                      <chr> "Educación Técnica", "Educa…
$ ultimo_colegio                             <chr> "Particular subvencionado",…
$ ea_01_horas_estudio_semana                 <chr> "3 o 4 horas al día", "3 o …
$ ea_02_horas_estudio_fin_semana             <chr> "Más de 7 horas por día", "…
$ ea_03_descripcion_carga_academica          <chr> "Pesada", "Moderada", "Mode…
$ ea_04_notas_ultimo_semestre                <dbl> 6.2, 5.5, 5.7, 5.4, 5.5, 5.…
$ ea_05_satisfaccion_rendimiento_academico   <chr> "Insatisfecho", "Insatisfec…
$ ea_06_nivel_estres_ultimo_semestre         <dbl> 4, 4, 1, 3, 4, 4, 4, 5, 4, …
$ ea_07_efecto_estres_rendimiento            <chr> "Mucho", "Bastante", "Poco"…
$ ea_08                                      <chr> "Si, se identificar cuando …
$ ea_09                                      <chr> "Dolores de Cabeza, Tensión…
$ ea_10                                      <chr> "Técnicas de relajación (co…
$ re_01                                      <chr> "Creencia firme", "Creencia…
$ re_02                                      <chr> "No tengo una afiliación re…
$ re_03                                      <chr> "A diario.", "Al menos una …
$ re_04                                      <chr> "Sí, asisto", "No, no he as…
$ re_05                                      <chr> "Moderadamente influyente",…
$ rs_01                                      <chr> "Entre 3 a 4 horas", "Entre…
$ rs_02                                      <chr> "Mantenerse en contacto con…
$ rs_03                                      <chr> "No", "No", "No", "No", "No…
$ rs_04                                      <chr> "Desconectándome temporalme…
$ rs_05                                      <chr> "Instagram", "Instagram", "…
$ rs_06                                      <chr> "WhatsApp", "WhatsApp", "Wh…
$ to_01                                      <chr> "Poco tiempo.", "Suficiente…
$ to_02                                      <chr> "1 a 2 veces.", "Más de 6."…
$ to_03                                      <chr> "No, no administro mi tiemp…
$ to_04                                      <chr> "Leer. y/o Escribir, Ver se…
$ to_05                                      <chr> "No, las realizo de forma i…
$ to_06                                      <chr> "Importante.", "Muy importa…
$ ma_01                                      <dbl> 1, 7, 1, 5, 5, 8, 7, 2, 5, …
$ ma_02                                      <dbl> 2, 9, 1, 7, 2, 7, 7, 4, 7, …
$ ma_03                                      <chr> "No", "No", "No", "No", "No…
$ ma_04                                      <chr> "No", "Sí", "No", "No", "No…
$ ma_05                                      <chr> "Alta frecuencia (usualment…
$ cm_01                                      <dbl> 7, 7, 7, 7, 6, 5, 7, 7, 7, …
$ cm_02                                      <chr> "Más de 7 horas.", "Entre 1…
$ cm_03                                      <chr> "Jazz", "Rock", "Metal", "R…
$ cm_04                                      <chr> "Boleros", "Electrónica", "…
$ cm_05                                      <chr> "En el transporte público, …
$ cm_06                                      <chr> "Muy importante", "Muy impo…
$ identidad_genero_r                         <chr> "Hombre cisgenero", "Mujer …
$ edad_r                                     <chr> "21 a 23", "18 a 20", "21 a…
$ año_ingreso_carrera_r                      <chr> "post-pandemia", "post-pand…
$ comuna_r1                                  <chr> "Periurbano", "Zona Sur", "…
$ comuna_distancia                           <chr> "Vive a mucha distancia", "…
$ horas_estudio_semana                       <chr> "3 o 4 horas al día", "3 o …
$ notas_ultimo_semestre_intervalo            <chr> "6.0 a 7.0", "5.0 a 5.9", "…
$ ea_05_satisfaccion_rendimiento_academico_r <chr> "Insatisfecho", "Insatisfec…
$ ea_06_nivel_estres_ultimo_semestre_r       <chr> "Estres Alto", "Estres Alto…
$ ea_07_efecto_estres_rendimiento_r          <chr> "Bastante", "Bastante", "Mo…

In [5]:
names(base)

 [1] "marca"
 [2] "direc"
 [3] "n_encuestador"
 [4] "sd_01"
 [5] "identidad_genero"
 [6] "edad"
 [7] "año_ingreso_carrera"
 [8] "comuna"
 [9] "clase_social"
[10] "nivel_educacion_padre"
[11] "nivel_educacion_madre"
[12] "ultimo_colegio"
[13] "ea_01_horas_estudio_semana"
[14] "ea_02_horas_estudio_fin_semana"
[15] "ea_03_descripcion_carga_academica"
[16] "ea_04_notas_ultimo_semestre"
[17] "ea_05_satisfaccion_rendimiento_academico"
[18] "ea_06_nivel_estres_ultimo_semestre"
[19] "ea_07_efecto_estres_rendimiento"
[20] "ea_08"
[21] "ea_09"
[22] "ea_10"
[23] "re_01"
[24] "re_02"
[25] "re_03"
[26] "re_04"
[27] "re_05"
[28] "rs_01"
[29] "rs_02"
[30] "rs_03"
[31] "rs_04"
[32] "rs_05"
[33] "rs_06"
[34] "to_01"
[35] "to_02"
[36] "to_03"
[37] "to_04"
[38] "to_05"
[39] "to_06"
[40] "ma_01"
[41] "ma_02"
[42] "ma_03"
[43] "ma_04"
[44] "ma_05"
[45] "cm_01"
[46] "cm_02"
[47] "cm_03"
[48] "cm_04"
[49] "cm_05"
[50] "cm_06"
[51] "identidad_genero_r"
[52] "edad_r"
[53] "año_ingreso_carrera_r"
[54] "comuna_r1"
[55] "comuna_distancia"
[56] "horas_estudio_semana"
[57] "notas_ultimo_semestre_intervalo"
[58] "ea_05_satisfaccion_rendimiento_academico_r"
[59] "ea_06_nivel_estres_ultimo_semestre_r"
[60] "ea_07_efecto_estres_rendimiento_r"

## **Distribución de frecuencias**
### Quiero saber ¿cuántas personas se identifican con cada género?
- Variable de interés: identidad de género recodificada _r

### Tabla simple con `table()`

In [6]:
table(base$identidad_genero_r)

         Hombre cisgenero           Mujer cisgenero Persona de genero diverso
                       42                        84                        21

### Distintas formas de hacer tablas de frecuencia:

# Forma 1: Con `freq()` de summarytools ####

In [13]:
freq(base$identidad_genero_r)

                          Freq % Valid   % Valid Cum. % Total   % Total Cum.
Hombre cisgenero           42   28.57143  28.57143     28.57143  28.57143
Mujer cisgenero            84   57.14286  85.71429     57.14286  85.71429
Persona de genero diverso  21   14.28571 100.00000     14.28571 100.00000
<NA>                        0         NA        NA      0.00000 100.00000
Total                     147  100.00000 100.00000    100.00000 100.00000

La tabla está algo desordenada: incluye frecuencias válidas y acumuladas por default, y aparecen los NA

In [27]:
# Filtramos los NA de forma directa y quitamos la fila <NA> del resultado
tabla_genero <- freq(base$identidad_genero_r[!is.na(base$identidad_genero_r)], prop = TRUE, order = "freq", report.nas = FALSE)

# Filtramos la fila <NA> del resultado final usando una exclusión simple por nombre
tabla_genero[rownames(tabla_genero) != "<NA>", ]

                          Freq % Valid   % Valid Cum. % Total   % Total Cum.
Mujer cisgenero            84   57.14286  57.14286     57.14286  57.14286
Hombre cisgenero           42   28.57143  85.71429     28.57143  85.71429
Persona de genero diverso  21   14.28571 100.00000     14.28571 100.00000
Total                     147  100.00000 100.00000    100.00000 100.00000

Si queremos además visualizar una tabla más elegante y formateada
Tabla formateada con `kable` (para formato HTML)

In [32]:
# 1. Generar la tabla de frecuencias de la variable identidad de género
tabla_genero_limpia <- freq(base$identidad_genero_r[!is.na(base$identidad_genero_r)], prop = TRUE, order = "freq", report.nas = FALSE)

# 2. Dar formato HTML a la tabla usando kableExtra
tabla_html_limpia <- tabla_genero_limpia %>%
  tb() %>%
  filter(tolower(as.character(.[, 1])) != "<na>") %>%
  kable(col.names = c("Género", "Frecuencia", "%", "% Acumulado"),
        caption = "Distribución de frecuencias de Género (Sin Valores Nulos)",
        digits = c(0, 0, 2, 2),
        format = "html") %>%
  kable_classic(full_width = FALSE, html_font = "Cambria")

# 3. Guardar la tabla en formato HTML dentro de la carpeta tablas
if(!dir.exists("tablas")) dir.create("tablas")
save_kable(tabla_html_limpia, "tablas/f_genero_limpia.html")

# Mostrar la tabla formateada en el notebook
tabla_html_limpia

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Distribución de frecuencias de Género (Sin Valores Nulos)</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Género </th>
   <th style="text-align:right;"> Frecuencia </th>
   <th style="text-align:right;"> % </th>
   <th style="text-align:right;"> % Acumulado </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Mujer cisgenero </td>
   <td style="text-align:right;"> 84 </td>
   <td style="text-align:right;"> 57.14 </td>
   <td style="text-align:right;"> 57.14 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Hombre cisgenero </td>
   <td style="text-align:right;"> 42 </td>
   <td style="text-align:right;"> 28.57 </td>
   <td style="text-align:right;"> 85.71 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Persona de genero diverso </td>
   <td style="text-align:right;"> 21 </td>
   <td style="text-align:right;"> 14.29 </td>
   <td style="text-align:right;"> 100.00 </td>
  </tr>
</tbody>
</table>

In [28]:
base %>%
  freq(identidad_genero_r, prop = TRUE, order = "freq", report.nas =  FALSE)%>%
  tb() %>%  #hace que se visualice
  kable(col.names = c("Género", "Frecuencia", "%", "% Acumulado"), #nombro las columnas
        caption = "Distribución de frecuencias de Género", #nombro la tabla
        digits = c(0, 0, 2, 2))%>%  #establezco decimales por columna
  kable_classic(full_width = F, html_font = "Cambria") #la tabla no debe ocupar todo el ancho, fuente cambria

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Distribución de frecuencias de Género</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Género </th>
   <th style="text-align:right;"> Frecuencia </th>
   <th style="text-align:right;"> % </th>
   <th style="text-align:right;"> % Acumulado </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Mujer cisgenero </td>
   <td style="text-align:right;"> 84 </td>
   <td style="text-align:right;"> 57.14 </td>
   <td style="text-align:right;"> 57.14 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Hombre cisgenero </td>
   <td style="text-align:right;"> 42 </td>
   <td style="text-align:right;"> 28.57 </td>
   <td style="text-align:right;"> 85.71 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Persona de genero diverso </td>
   <td style="text-align:right;"> 21 </td>
   <td style="text-align:right;"> 14.29 </td>
   <td style="text-align:right;"> 100.00 </td>
  </tr>
</tbody>
</table>

In [35]:
# Colab está imprimiendo el código HTML crudo en vez de interpretarlo y renderizarlo como una tabla visual
# Renderizamos el código HTML para que se vea como tabla formateada en Colab
IRdisplay::display_html(as.character(tabla_html_limpia))

Género,Frecuencia,%,% Acumulado
Mujer cisgenero,84,57.14,57.14
Hombre cisgenero,42,28.57,85.71
Persona de genero diverso,21,14.29,100.00

### Guardar la tabla en formato HTML

In [36]:
#Cargar librerías necesarias
library(knitr)
library(kableExtra)

### Crear tabla

In [37]:
tabla_html <- base %>%
  freq(identidad_genero_r, prop = TRUE, order = "freq", report.nas = FALSE) %>%
  tb() %>%
  kable(col.names = c("Género", "Frecuencia", "%", "% Acumulado"),
        caption = "Distribución de frecuencias de Género",
        digits = c(0, 0, 2, 2),
        format = "html") %>%
  kable_classic(full_width = FALSE, html_font = "Cambria")

### Creamos carpeta si no existe

In [38]:
if(!dir.exists("tablas")) dir.create("tablas")
# La carpeta que creamos llamada "tablas" se ha guardado directamente en el directorio de trabajo actual de la sesión de Google Colab

In [40]:
# Acceso directo mejorado y seguro para descargar archivos de la carpeta 'tablas'
archivos <- list.files("tablas", full.names = TRUE)

if (length(archivos) == 0) {
  cat("La carpeta 'tablas' está vacía o aún no se han generado archivos.\n")
} else {
  cat("=== ENLACES DE DESCARGA DIRECTA ===\n")
  for (archivo in archivos) {
    nombre_archivo <- basename(archivo)
    ext <- tools::file_ext(nombre_archivo)

    # Determinar el tipo MIME correcto para la descarga
    mime <- switch(ext,
      "html" = "text/html",
      "xlsx" = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "png"  = "image/png",
      "application/octet-stream"
    )

    # Leer el archivo en binario y codificarlo en Base64 de manera segura
    con <- file(archivo, "rb")
    bytes <- readBin(con, "raw", n = file.info(archivo)$size)
    close(con)

    base64_data <- jsonlite::base64_enc(bytes)

    # Generar un botón de descarga HTML nativo y seguro que no requiere conexión externa
    html_button <- sprintf(
      '<p style="margin: 8px 0;">📂 <a href="data:%s;base64,%s" download="%s" style="background-color: #1a73e8; color: white; padding: 6px 12px; text-decoration: none; border-radius: 4px; font-weight: bold; display: inline-block; font-size: 13px; box-shadow: 0 1px 3px rgba(0,0,0,0.2);">Descargar %s</a></p>',
      mime, base64_data, nombre_archivo, nombre_archivo
    )

    IRdisplay::display_html(html_button)
  }
}

=== ENLACES DE DESCARGA DIRECTA ===

### Guardar como archivo HTML

In [41]:
save_kable(tabla_html, "tablas/f_genero1.html")

# Aún no existe la tabla como un archivo independiente en el computador, sino que creamos su diseño dentro de la memoria temporal de R
# Con esta función podemos exportar y materializar esa tabla que está en la memoria y escribirla físicamente en el almacenamiento como un archivo .html o una imagen .png

### Pasos para ver la carpeta "tablas" y los archivos guardados en google colab:

- 1. Ve a la barra lateral izquierda de tu pantalla en Google Colab.
- 2. Haz clic en el ícono de la Carpeta (📁) para abrir el explorador de archivos.
- 3. Verás una carpeta llamada tablas

## En formato Excell
Guardamos la tabla sin utilizar Kable

* Creamos la tabla como **data.frame**

In [42]:
f_genero1_df <- base %>%
  freq(identidad_genero_r, prop = TRUE, order = "freq", report.nas = FALSE) %>%
  tb() %>%
  rename(Género = 1, Frecuencia = 2, Porcentaje = 3, Porcentaje_acumulado = 4) %>%
  mutate(Porcentaje = round(Porcentaje, 2),
         Porcentaje_acumulado = round(Porcentaje_acumulado, 2))

Guardamos como archivo Excel correctamente

In [43]:
write.xlsx(f_genero1_df, "tablas/f_genero1.xlsx")

Si quieres mostrarla bonita en pantalla ahora sí usas kable:

In [44]:
f_genero1_df %>%
  kable(col.names = c("Género", "Frecuencia", "%", "% Acumulado"),
        caption = "Distribución de frecuencias de Género",
        digits = c(0, 0, 2, 2)) %>%
  kable_classic(full_width = F, html_font = "Cambria")

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>Distribución de frecuencias de Género</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Género </th>
   <th style="text-align:right;"> Frecuencia </th>
   <th style="text-align:right;"> % </th>
   <th style="text-align:right;"> % Acumulado </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Mujer cisgenero </td>
   <td style="text-align:right;"> 84 </td>
   <td style="text-align:right;"> 57.14 </td>
   <td style="text-align:right;"> 57.14 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Hombre cisgenero </td>
   <td style="text-align:right;"> 42 </td>
   <td style="text-align:right;"> 28.57 </td>
   <td style="text-align:right;"> 85.71 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Persona de genero diverso </td>
   <td style="text-align:right;"> 21 </td>
   <td style="text-align:right;"> 14.29 </td>
   <td style="text-align:right;"> 100.00 </td>
  </tr>
</tbody>
</table>

In [ ]:
# Esto funciona bien directamente en Rtudio, pero acá en Colab habrá que utilizar IRdisplay

# Forma 2: con tidyverse
Con este código vamos a generar una tabla de frecuencias y porcentajes de la variable identidad de género.
Este proceso incluye: filtrar valores perdidos, contar frecuencias, calcular porcentajes,
redondear decimales, ordenar los resultados, renombrar columnas y agregar una fila de Total.

In [47]:
f_genero2 <- base %>%
  filter(!is.na(identidad_genero_r)) %>% # filtramos para eliminar los casos con NA (sin respuesta)
  count(identidad_genero_r) %>% # contamos cuántas veces aparece cada categoría de identidad de género
  mutate(Porcentaje = n / sum(n) * 100) %>% # generamos el porcentaje respecto del total
  mutate(Porcentaje = round(Porcentaje, 2)) %>% # redondeamos los porcentajes a dos decimales
  arrange(desc(Porcentaje)) %>% # ordenamos los resultados de mayor a menor porcentaje
  rename(Frecuencia = n, Genero = identidad_genero_r) %>% # renombramos las columnas para mayor claridad
  bind_rows(list(Genero = "Total", Frecuencia = sum(.$Frecuencia), Porcentaje = 100))

Agregamos una fila final que indica el total de respuestas, con 100% como porcentaje
La función bind_rows nos permite agregar una fila de Total al final, lo que facilita la lectura.

### Exportamos la tabla a Excel en la carpeta "tablas" que creamos antes

In [ ]:
write.xlsx(f_genero2, "tablas/f_genero2.xlsx")

### Exportamos la tabla a HTML en la carpeta "tablas"

In [ ]:
library(kableExtra)

### Crear la tabla HTML

In [ ]:
tabla_html <- f_genero2 %>%
  kable(format = "html",
        col.names = c("Género", "Frecuencia", "Porcentaje"),
        caption = "Distribución de identidades de género",
        digits = c(0, 0, 2)) %>%
  kable_classic(full_width = FALSE, html_font = "Cambria")

### Guardar como archivo HTML

In [ ]:
save_kable(tabla_html, file = "tablas/f_genero2.html")

# Tablas de contingencia (cruce 2 variables)

In [ ]:
#Cargar las bibliotecas necesarias
library(knitr)
library(kableExtra)
library(webshot2)
library(gmodels)

## Forma 1: Mediante `ctable()`

a) Elegir nuestras variables para el cruce y hacer la tabla con estas
Si nos preguntamos
¿Qué religiones son más frecuentes en ciertos colegios?
Esta tabla de contingencia presenta la distribución de las afiliaciones religiosas según el último colegio
cómo varía o se mantiene la proporción de religiones en los diferentes colegios.
variables: ultimo_colegio y re_02: afiliación religiosa

Tabla de contingencia simple

In [ ]:
summarytools::ctable( x = base$re_02, y = base$ultimo_colegio)

Nos entrega las frecuencias absolutas (conteo de casos por combinación), las proporciones marginales (por fila y columna),
y los totales por fila y por columna
Podemos ver que queda una tabla muy desordenada y compleja de entender

Obtener proporciones por columna:

In [ ]:
ctable( x = base$re_02, y = base$ultimo_colegio, prop = "c", justify = "l")

Indica que las proporciones deben calcularse por columna ("column-wise proportions")
Esto es útil cuando quieres analizar cómo se distribuyen las respuestas dentro de cada columna
por ejemplo, qué proporción de estudiantes de colegio particular pertenece a cada religión.
justify = "l" alinea el texto a la izquierda dentro de la tabla ("l" de left).
Nos damos cuenta de que la tabla, si bien es entendible, tiene mucha información, muchas categorías,
por lo que es compleja de entender

### b) Recodificamos las categorías para dejar menos cantidad de categorías de respuesta con MUTATE
- Para la variable re_02

In [ ]:
#Vemos categorías de respuesta de re_02
unique(base$re_02)

### Recodificamos categorías con mutate

In [ ]:
base <- base %>%
  mutate(re_02 = case_when(re_02 ==  "Yoruba " ~ "Otra",
                           re_02 ==  "Grecorromana " ~ "Otra",
                           re_02 ==  "Grecorromana" ~ "Otra",
                           re_02 ==  "Ortodoxo" ~ "Ortodoxa",
                           re_02 ==  "Cristianismo Protestante (Evangélico, anglicano, etcétera)" ~ "Cristianismo protestante",
                           re_02 ==  "No tengo afiliaciones religiosas y tampoco me adscribo a ningún tipo de corriente de pensamiento de tipo clasificatoria" ~ "Ninguna",
                           re_02 ==  "Catolico" ~ "Catolicismo",
                           re_02 ==  "deísmo" ~ "Deísmo",
                           re_02 ==  "Agnóstico" ~ "Agnóstico/a",
                           re_02 ==  "Ateo" ~ "Ninguna",
                           re_02 ==  "Ninguno " ~ "Ninguna",
                           re_02 ==  "Pagana" ~ "Otra",
                           re_02 ==  "No tengo una afiliación religiosa, pero si me considero una persona espiritual (por ejemplo, creo en las energías)." ~ "Otra",
                           re_02 ==  "seria en creer en alguien superior un tipo de energía que se interpreta de diversas formas en la religión pero no es alguien al cual se le pueda poner un nombre" ~ "Otra",
                           TRUE ~ re_02))

### Verificamos

In [ ]:
unique(base$re_02)

### c) Filtramos NA y Ordenamos
En este caso no será necesario pues no hay valores NA

### Para ordenar categorías...

In [ ]:
#Observamos el tipo de variable
class(base$re_02)

Es una variable character, pero debemos transformarla a variable factor para poder ordenarla

In [ ]:
#Transformamos a factor
base <- base %>%
  mutate(re_02 = as.factor(re_02))

In [ ]:
#Ordenamos categorías
base$re_02 <- base$re_02 %>% fct_relevel(c("Catolicismo", "Cristianismo protestante",
                                           "Agnóstico/a", "Ninguna", "Otra"))

### Verificamos

In [ ]:
unique(base$re_02)

Fíjense en el levels

### d) Crear la tabla cruzada con ctable

In [ ]:
ctable(x = base$re_02,
       y = base$ultimo_colegio,
       prop = "c", #proporciones por columna
       justify = "l") #texto hacia la izquierda

### e) Interpretar
El grupo "Otra" es el más común en todos los tipos de colegio, especialmente en el subvencionado (45%).
Los colegios particulares tienen más personas sin religión ("Ninguna"): 28,6%.
Los colegios públicos tienen un poco más de agnósticos (25,6%).
Las religiones institucionales (católica y protestante) no superan juntas el 12% en ningún tipo de colegio.

# Forma 2: Mediante prop.table()
### a) Elegir nuestras variables para el cruce y hacer la tabla con estas
Si nos preguntamos ¿Qué religiones predominan en ciertos estratos de clase?
la tabla muestra cómo se distribuyen las afiliaciones religiosas según la clase social
- Variables: clase_social y re_01

### b) Crear la tabla y guardarla en el enviroment

In [ ]:
tabla_rel_clase <- base  %>%
  select(Religión = re_01, `Clase Social` = clase_social) %>%  # Seleccionar y renombrar las variables
  droplevels() %>% # Eliminar las categorías que no se utilizan en la columna
  table(.) %>%# Hacer una tabla con todos los datos
  addmargins(.,2) %>% # Calcular los porcentajes por columnas
  prop.table(.) %>% # Agregar total de columnas
  round(4)*100  # Formatear y redondear con símbolo de porcentaje

### c) Interpretar y sacar conclusiones

### d) Guardar en un excel

In [ ]:
write.xlsx(tabla_rel_clase, "tablas/tabla_rel_clase.xlsx")

### e) Guardar en PNG

In [ ]:
tabla_rel_clase %>%
  kable(., caption="Tabla de contingencia para religión y clase social (% por columnas)") %>%
  kable_classic(full_width = F, html_font = "Cambria", font_size = 15) %>%
  save_kable(file = "tablas/tabla_rel_clase.png", zoom = 2)