# Métodos cuantitativos II
## Ayudantía N°1: Repaso Tidyverse

##### En este curso trabajaremos en Google collab, que funciona como un entorno de trabajo que permite **ejecutar el lenguaje en R desde la nube de google drive**.


### ¿Qué haremos hoy?
- Repasar `select()` y `filter()`
- Introducir otras herramientas tidyverse: `mutate()`, `arrange()` y `count()`
- Practicar pensando en la lógica del lenguaje R

Antes de comenzar, recuerda la lógica general:

**Pregunta → ¿Qué necesito hacer con los datos? → Código → Resultado → Interpretación**

## 1. Preparar nuestro espacio de trabajo: Instalar y cargar paquetes

##### En este caso instalaremos tidyverse únicamente

In [3]:
# Instalar tidyverse y cargarlo
install.packages("tidyverse")
library(tidyverse)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

## 2. Nuestra base de datos: contiene los datos que vamos a analizar

Para esta ayudantía trabajaremos con una base ficticia (creada mediante código) de una encuesta sobre **prácticas culturales, uso del tiempo y participación social**.

In [4]:
# Base de datos de ejemplo
set.seed(123)

datos <- tibble(
  id = 1:100,
  edad = sample(18:70, 100, replace = TRUE),
  comuna = sample(c("Santiago", "Maipu", "Ñuñoa", "Recoleta", "Puente Alto"), 100, replace = TRUE),
  situacion_laboral = sample(c("Trabaja", "Estudia", "Trabaja y estudia", "No trabaja"), 100, replace = TRUE),
  horas_trabajo = sample(0:50, 100, replace = TRUE),
  horas_estudio = sample(0:35, 100, replace = TRUE),
  participacion_organizacion = sample(0:5, 100, replace = TRUE),
  satisfaccion_vida = sample(1:10, 100, replace = TRUE)
)

## Exploración de datos

In [5]:
glimpse(datos)

Rows: 100
Columns: 8
$ id                         <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, …
$ edad                       <int> 48, 32, 68, 31, 20, 59, 67, 60, 54, 69, 31,…
$ comuna                     <chr> "Santiago", "Ñuñoa", "Puente Alto", "Ñuñoa"…
$ situacion_laboral          <chr> "No trabaja", "Trabaja", "Trabaja", "Trabaj…
$ horas_trabajo              <int> 34, 35, 26, 26, 34, 22, 2, 30, 47, 1, 46, 2…
$ horas_estudio              <int> 5, 15, 14, 18, 2, 32, 32, 10, 35, 9, 23, 27…
$ participacion_organizacion <int> 1, 3, 5, 0, 4, 4, 2, 5, 2, 5, 4, 0, 3, 1, 4…
$ satisfaccion_vida          <int> 3, 5, 2, 1, 4, 4, 10, 10, 5, 6, 4, 3, 3, 1,…

###  ¿Cuántas filas y columnas tiene nuestra base?

In [6]:
dim(datos)

[1] 100   8

# 3. Seleccionar variables → `select()`

**Pregunta:** ¿Cómo completamos este código si queremos explorar la posibles vinculaciones entre edad, situación laboral y nivel de participación en alguna(s) organización(es)?

In [7]:
# Completa el código:
datos %>%
  select(edad, situacion_laboral, participacion_organizacion)

    edad situacion_laboral participacion_organizacion
1   48   No trabaja        1
2   32   Trabaja           3
3   68   Trabaja           5
4   31   Trabaja           0
5   20   Trabaja           4
6   59   Trabaja y estudia 4
7   67   Estudia           2
8   60   Estudia           5
9   54   Estudia           2
10  69   Trabaja y estudia 5
11  31   Trabaja           4
12  42   Estudia           0
13  43   Estudia           3
14  44   Trabaja           1
15  22   Estudia           4
16  68   Trabaja           5
17  44   Trabaja           3
18  45   Estudia           5
19  26   Trabaja y estudia 4
20  46   Trabaja           0
21  52   Trabaja y estudia 1
22  25   No trabaja        2
23  43   Trabaja           0
24  24   Estudia           0
25  59   Trabaja           2
26  26   No trabaja        1
27  36   Estudia           3
28  53   Estudia           4
29  31   Estudia           2
30  34   Trabaja y estudia 3
⋮   ⋮    ⋮                 ⋮
71  47   No trabaja        4
72  23   Estudia           3
73  60   Trabaja           1
74  25   Trabaja           5
75  39   Trabaja           0
76  39   Estudia           3
77  56   Trabaja           0
78  48   Estudia           2
79  65   Trabaja           0
80  34   No trabaja        2
81  67   Trabaja           2
82  66   Trabaja y estudia 1
83  51   Trabaja y estudia 2
84  21   Estudia           5
85  30   Estudia           3
86  22   Trabaja           1
87  68   Trabaja y estudia 0
88  42   No trabaja        4
89  69   Trabaja           2
90  39   Trabaja           3
91  42   Estudia           4
92  49   Trabaja           5
93  63   Estudia           4
94  42   Estudia           5
95  40   Estudia           3
96  52   Estudia           5
97  57   No trabaja        0
98  65   No trabaja        0
99  47   No trabaja        3
100 29   No trabaja        5

### 📌 Pregunta

¿Qué estamos dejando fuera cuando aplicamos `select()`?

- ¿Personas/casos?
- ¿Variables/columnas?

# 4. Filtrarar casos → `filter()`

**Pregunta:** ¿Cómo podemos quedarnos solamente con las personas menores de 30 años?

In [8]:
datos %>%
  filter(edad < 30)

   id  edad comuna      situacion_laboral horas_trabajo horas_estudio
1    5 20   Maipu       Trabaja           34             2
2   15 22   Recoleta    Estudia           38            19
3   19 26   Ñuñoa       Trabaja y estudia  8             4
4   22 25   Puente Alto No trabaja        21             9
5   24 24   Ñuñoa       Estudia           40             8
6   26 26   Puente Alto No trabaja        28             5
7   34 29   Santiago    Trabaja           11             3
8   39 24   Ñuñoa       Estudia           29            35
9   40 26   Recoleta    Trabaja           34            29
10  42 27   Santiago    No trabaja        24            24
11  46 24   Recoleta    Trabaja           50            14
12  54 22   Ñuñoa       Estudia           31            15
13  55 25   Recoleta    Trabaja y estudia 25             8
14  56 29   Ñuñoa       Estudia           12            10
15  72 23   Maipu       Estudia           41            16
16  74 25   Maipu       Trabaja           48             5
17  84 21   Santiago    Estudia           29             1
18  86 22   Puente Alto Trabaja           15             6
19 100 29   Puente Alto No trabaja        50             1
   participacion_organizacion satisfaccion_vida
1  4                           4
2  4                           7
3  4                           9
4  2                           5
5  0                           8
6  1                           6
7  5                           8
8  0                           4
9  4                           9
10 1                           4
11 0                           8
12 0                          10
13 3                           7
14 0                           5
15 3                           4
16 5                           5
17 5                           9
18 1                           9
19 5                           2

### ¿Qué ocurrirá con el número de filas?

- Aumentará
- Disminuirá
- Se mantendrá igual

## 5. Combinar `filter()` + `select()`

Ahora queremos estudiar **solamente a las personas menores de 30 años**, pero mirando únicamente su edad, situación laboral y nivel de participación en alguna organización(es).

In [9]:
datos %>%
  filter(edad < 30) %>%
  select(edad, situacion_laboral, participacion_organizacion)

   edad situacion_laboral participacion_organizacion
1  20   Trabaja           4
2  22   Estudia           4
3  26   Trabaja y estudia 4
4  25   No trabaja        2
5  24   Estudia           0
6  26   No trabaja        1
7  29   Trabaja           5
8  24   Estudia           0
9  26   Trabaja           4
10 27   No trabaja        1
11 24   Trabaja           0
12 22   Estudia           0
13 25   Trabaja y estudia 3
14 29   Estudia           0
15 23   Estudia           3
16 25   Trabaja           5
17 21   Estudia           5
18 22   Trabaja           1
19 29   No trabaja        5

### Operadores lógicos

Podemos combinar condiciones con `&` (Y) y `|` (O).

Por ejemplo: personas mayores de 25 años **Y** que viven en Santiago.

In [10]:
datos %>%
  filter(edad > 25 & comuna == "Santiago")

   id edad comuna   situacion_laboral horas_trabajo horas_estudio
1   1 48   Santiago No trabaja        34             5
2  17 44   Santiago Trabaja           30            10
3  20 46   Santiago Trabaja           35            28
4  34 29   Santiago Trabaja           11             3
5  36 49   Santiago No trabaja        20            27
6  42 27   Santiago No trabaja        24            24
7  44 44   Santiago Trabaja           46            24
8  52 51   Santiago Trabaja           39             7
9  57 30   Santiago Trabaja y estudia 19            29
10 63 38   Santiago Trabaja           40            17
11 71 47   Santiago No trabaja        50             9
12 73 60   Santiago Trabaja           10             5
13 77 56   Santiago Trabaja           18            34
14 85 30   Santiago Estudia            9             9
15 94 42   Santiago Estudia           11            10
16 97 57   Santiago No trabaja        49            32
   participacion_organizacion satisfaccion_vida
1  1                          3
2  3                          7
3  0                          8
4  5                          8
5  1                          9
6  1                          4
7  5                          7
8  0                          4
9  2                          8
10 3                          3
11 4                          1
12 1                          1
13 0                          2
14 3                          7
15 5                          8
16 0                          4

In [12]:
datos %>%
  filter(edad > 18 & edad < 30 & situacion_laboral == "Trabaja y estudia")

  id edad comuna   situacion_laboral horas_trabajo horas_estudio
1 19 26   Ñuñoa    Trabaja y estudia  8            4
2 55 25   Recoleta Trabaja y estudia 25            8
  participacion_organizacion satisfaccion_vida
1 4                          9
2 3                          7

# 6. Crear/modificar variables → `mutate()`

Ahora pasamos de **seleccionar y filtrar** a **transformar los datos**.

Si tenemos horas de trabajo y horas de estudio, podemos crear una variable que aproxime las horas de tiempo libre (si lo contemplamos como tiempo no trabajado ni estudiado) trabajo/estudio disponibles en un día

In [ ]:
datos %>%
  mutate(
    horas_disponibles = 24 - horas_trabajo - horas_estudio
  )

### 📌 Pregunta

Queremos crear una variable que indique si una persona tiene **participación alta** en alguna organización(es), considerando alta una puntuación igual o superior a 3.

¿Qué código escribirías?

In [ ]:
# Intenta antes de mirar la solución
datos %>%
  mutate(
    participacion_alta = participacion_organizacion >= 3
  )

# 7. Ordenar casos → `arrange()`

Queremos encontrar primero a quienes tienen **más horas de trabajo**.

In [ ]:
datos %>%
  arrange(desc(horas_trabajo))

### 🔎 ¿Qué diferencia hay?

Compara mentalmente:

```r
arrange(horas_trabajo)
```

y

```r
arrange(desc(horas_trabajo))
```

# 8. Contar casos → `count()`

**Pregunta:** ¿Cómo se distribuyen las personas de nuestra muestra según situación laboral?

In [ ]:
datos %>%
  count(situacion_laboral)

### Otra pregunta

¿Cómo se distribuye la participación en organizaciones?

In [ ]:
datos %>%
  count(participacion_organizacion, sort = TRUE)

#  11. Para llevarnos hoy: Conclusiones

| Quiero... | Uso... |
|---|---|
| Elegir variables | `select()` |
| Elegir casos | `filter()` |
| Crear o transformar variables | `mutate()` |
| Ordenar casos | `arrange()` |
| Contar casos | `count()` |

### Idea central

**No empezamos por el código. Empezamos por una pregunta sobre los datos.**